"""create resume screening tables

Revision ID: ec7c624032bc
Revises: 
Create Date: 2026-09-08 12:28:08.847929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec7c624032bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('screening_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_runs_id'), 'screening_runs', ['id'], unique=False)
    op.create_index(op.f('ix_screening_runs_user_id'), 'screening_runs', ['user_id'], unique=False)
    op.create_table('screening_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screening_run_id', sa.Integer(), nullable=True),
    sa.Column('candidate_name', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('skill_score', sa.Float(), nullable=False),
    sa.Column('preferred_skill_score', sa.Float(), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('education_score', sa.Float(), nullable=False),
    sa.Column('seniority_score', sa.Float(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False),
    sa.Column('matched_skills', sa.Text(), nullable=False),
    sa.Column('missing_skills', sa.Text(), nullable=False),
    sa.Column('resume_skills', sa.Text(), nullable=False),
    sa.Column('job_required_skills', sa.Text(), nullable=False),
    sa.Column('job_preferred_skills', sa.Text(), nullable=False),
    sa.Column('candidate_seniority', sa.String(length=100), nullable=True),
    sa.Column('required_seniority', sa.String(length=100), nullable=True),
    sa.Column('explanation_summary', sa.Text(), nullable=False),
    sa.Column('explanation_strengths', sa.Text(), nullable=False),
    sa.Column('explanation_concerns', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['screening_run_id'], ['screening_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_results_id'), 'screening_results', ['id'], unique=False)
    op.create_index(op.f('ix_screening_results_screening_run_id'), 'screening_results', ['screening_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screening_results_screening_run_id'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_id'), table_name='screening_results')
    op.drop_table('screening_results')
    op.drop_index(op.f('ix_screening_runs_user_id'), table_name='screening_runs')
    op.drop_index(op.f('ix_screening_runs_id'), table_name='screening_runs')
    op.drop_table('screening_runs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
